### ISSUE TITLE
/fdc on not working

### ISSUE THREAD

**Issue by 1bnetworth** [unkwns/FDC#1]
/fdc on isn't working I launched my game and it isn't working

**Comment by unkwns** [comment]
Hello 1bnetworth, have you restarted your game? Maybe an error occurred through the launcher? Let me know if that helps!

**Comment by 1bnetworth** [comment]
> Hello 1bnetworth, have you restarted your game? Maybe an error occurred through the launcher? Let me know if that helps!

yo thanks dude i'll try that now

**Comment by 1bnetworth** [comment]
> Hello 1bnetworth, have you restarted your game? Maybe an error occurred through the launcher? Let me know if that helps!

so before i restarted my game all the commands werent working now only /fdc config is working and has a bunch of options and idk how to fix it

**Comment by 1bnetworth** [comment]
> > > Hello 1bnetworth, have you restarted your game? Maybe an error occurred through the launcher? Let me know if that helps!
> > 
> > 
> > so before i restarted my game all the commands werent working now only /fdc config is working and has a bunch of options and idk how to fix it
> 
> Hello again, if you are in the config gui click on the magnifying glass and search legacy. Make sure to enable legacy settings if those aren't already enabled or click refresh mod config.

hey man im on legacy now and its working thanks dude

**Comment by unkwns** [comment]
> > > > Hello 1bnetworth, have you restarted your game? Maybe an error occurred through the launcher? Let me know if that helps!
> > > 
> > > 
> > > so before i restarted my game all the commands werent working now only /fdc config is working and has a bunch of options and idk how to fix it
> > 
> > 
> > Hello again, if you are in the config gui click on the magnifying glass and search legacy. Make sure to enable legacy settings if those aren't already enabled or click refresh mod config.
> 
> hey man im on legacy now and its working thanks dude

No problem. Make sure to star the project if you enjoy the mod to push it out to more people!
